// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reference.Infrastructure.DBContext;

#nullable disable

namespace Reference.Infrastructure.DBContext.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("20260404134451_adding table in reference api")]
    partial class addingtableinreferenceapi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reference.Domain.Model.AuctionEvent", b =>
                {
                    b.Property<long>("AuctionEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuctionEventId"));

                    b.Property<long>("ActionHouseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockId")
                        .HasColumnType("int");

                    b.Property<long>("OrganizerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuctionEventId");

                    b.HasIndex("ActionHouseId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("AuctionEvent");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionHouse", b =>
                {
                    b.Property<long>("AuctionHouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuctionHouseId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionHouseId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("AuctionHouse");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionItem", b =>
                {
                    b.Property<long>("AuctionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuctionItemId"));

                    b.Property<long?>("AuctionHouseId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("decimal(24,9)");

                    b.Property<short?>("Category")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.HasKey("AuctionItemId");

                    b.HasIndex("AuctionHouseId");

                    b.ToTable("AuctionItem");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionParticipant", b =>
                {
                    b.Property<long>("AuctionParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuctionParticipantId"));

                    b.Property<long>("AuctionEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockId")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionParticipantId");

                    b.HasIndex("AuctionEventId");

                    b.HasIndex("UserId");

                    b.ToTable("AuctionParticipant");
                });

            modelBuilder.Entity("Reference.Domain.Model.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<short?>("Category")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LockId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionEvent", b =>
                {
                    b.HasOne("Reference.Domain.Model.AuctionHouse", "AuctionHouse")
                        .WithMany("AuctionEvents")
                        .HasForeignKey("ActionHouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AuctionEvent_AuctionHouse_ActionHouseId");

                    b.HasOne("Reference.Domain.Model.User", "Organizer")
                        .WithMany("AuctionEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AuctionEvent_User_OrganizerId");

                    b.Navigation("AuctionHouse");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionHouse", b =>
                {
                    b.HasOne("Reference.Domain.Model.User", "User")
                        .WithMany("AuctionHouses")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AuctionHouse_User_OwnerUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionItem", b =>
                {
                    b.HasOne("Reference.Domain.Model.AuctionHouse", "AuctionHouse")
                        .WithMany("AuctionItems")
                        .HasForeignKey("AuctionHouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AuctionItem_AuctionHouse_AuctionHouseId");

                    b.Navigation("AuctionHouse");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionParticipant", b =>
                {
                    b.HasOne("Reference.Domain.Model.AuctionEvent", "AuctionEvent")
                        .WithMany("AuctionParticipants")
                        .HasForeignKey("AuctionEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AuctionParticipant_AuctionEvent_AuctionEventId");

                    b.HasOne("Reference.Domain.Model.User", "User")
                        .WithMany("AuctionParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AuctionParticipant_User_UserId");

                    b.Navigation("AuctionEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionEvent", b =>
                {
                    b.Navigation("AuctionParticipants");
                });

            modelBuilder.Entity("Reference.Domain.Model.AuctionHouse", b =>
                {
                    b.Navigation("AuctionEvents");

                    b.Navigation("AuctionItems");
                });

            modelBuilder.Entity("Reference.Domain.Model.User", b =>
                {
                    b.Navigation("AuctionEvents");

                    b.Navigation("AuctionHouses");

                    b.Navigation("AuctionParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
